### PR TITLE
Working app with normalisation

### PR DESCRIPTION
**Pull request by Addy81**
This app takes in the tso500 genomic vcf, filters reference calls out and filters whitelist variants from a given vcf.

Example job:

https://platform.dnanexus.com/projects/G5697p84YV3xyf6j4byQG3zp/monitor/job/G858yZ84YV3ZjPbz9V84fP36

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2)

### CODE REVIEW

**Review by woook — CHANGES_REQUESTED** [review]
This output has been archived so I can't look at it.

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-:-MvzRuvz0SBtVBRlbg4q:b-j1anqt)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @Addy81 and @woook)

___
*[dxapp.json, line 28 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzIz13EViGpzmjPvHZ:-MvzIz14DUzaUMIhTR7E:b-ioanio) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/dxapp.json#L28)):*
> ```JSON
>         "*vcf.gz"
>       ],
>       "help": "Compressed whitelist vcf"
> ```

I though we were trying to avoid the term whitelist now?
How about changing this to rescue vcf?



_Code quote:_
```JSON
whitelist
```
___
*[dxapp.json, line 99 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzJVOB-UeF5kZfxATm:-MvzJVOB-UeF5kZfxATn:b-2tlrzq) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/dxapp.json#L99)):*
> ```JSON
>     }
>   }
> }
> ```

No new line at end of file
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline
___
*[README.md, line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzKBS71-5CmaC_GM0c:-MvzKBS71-5CmaC_GM0d:b2txvxi) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/README.md#L6)):*
> ```Markdown
> ## What does this app do?
> 
> It takes the genomic vcf which is outputed by the TSO500 local app v2.2 and filters out the reference calls and low support variants but keeps low support variants that are present in a given whitelist.
> ```

rescue list



_Code quote:_
```Markdown
whitelist
```
___
*[README.md, line 9 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzK8dEEtEvYmgTTJT0:-MvzK8dEEtEvYmgTTJT1:b2txvxi) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/README.md#L9)):*
> ```Markdown
> 
> ## What are typical use cases for this app
> During the validation of the TSO500 local app v2.2 analysis pipeline, some known variants were excluded during filtering. This app attempts to rescue in filtered out variants if they are a known variant of interest given a whitelist of variants.
> ```

rescue list



_Code quote:_
```Markdown
whitelist
```
___
*[README.md, line 14 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzKFB21ubuvYevxCi4:-MvzKFB21ubuvYevxCi5:b2txvxi) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/README.md#L14)):*
> ```Markdown
> Required inputs for this app:
> * a genomic gvcf (*.genome.vcf)
> * a compressed whitelist vcf containing variants needed to always be filtered in (*.vcf.gz)
> ```

rescue list



_Code quote:_
```Markdown
whitelist
```
___
*[README.md, line 18 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzKJJP1R3mlVwnLXW0:-MvzKJJP1R3mlVwnLXW1:b2txvxi) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/README.md#L18)):*
> ```Markdown
> ## What does this app output?
> This app outputs:
> * a vcf file with all PASS variants in addition to filtered in low quality variants given a whitelist of variants provided.
> ```

rescue list



_Code quote:_
```Markdown
whitelist
```
___
*[README.md, line 22 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzKQIJDItG1wkhlaXe:-MvzKQIJDItG1wkhlaXf:b36x7hh) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/README.md#L22)):*
> ```Markdown
> This is the source code for an app that runs on the DNAnexus Platform.
> For more information about how to run or modify it, see
> https://documentation.dnanexus.com/.
> ```

No new line at end of file



_Code quote:_
```Markdown
.
```
___
*[src/eggd_tso500_rescue.sh, line 48 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzQbzk9DoZP6D0rSC6:-MvzQbzk9DoZP6D0rSC7:b-euwid) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/src/eggd_tso500_rescue.sh#L48)):*
> ```Shell
> 
>     # Add OPA flag to everything in that vcf
>     bcftools filter -e 'FORMAT/DP>0' -s OPA -m + ${sample_prefix}_filtered_hotspots.vcf.gz \
> ```

I'm being dim but what does this do?



_Code quote:_
```Shell
-e 'FORMAT/DP>0'
```
___
*[src/eggd_tso500_rescue.sh, line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzQp3JCFR8_t_-Ajg1:-MvzQp3JCFR8_t_-Ajg2:b3b25jm) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/src/eggd_tso500_rescue.sh#L55)):*
> ```Shell
>     # Concatenate OPA flagged non-pass variant vcf with pass vcf
>     bcftools concat -a  ${sample_prefix}_pass.vcf.gz ${sample_prefix}_OPAvariants.vcf.gz \
>     -o ${sample_prefix}_withLowSupportHotspots.vcf
> ```

Is there a reason that this isn't gzipped?



_Code quote:_
```Shell
vcf
```

**Review by Addy81 — COMMENTED** [review]
I thought if there has been stuff going on a project that it would be smart and not archive? Can we unarchive the project as this is the one I'm testing VEP and the rescue app or do i have to make a new one?

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-:-Mw11jjFEpowC4MrkGR4:b-h980q7)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @woook)

___
*[dxapp.json, line 28 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzIz13EViGpzmjPvHZ:-Mw11wIUApoHBvMAcrQ9:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/dxapp.json#L28)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

I though we were trying to avoid the term whitelist now?
How about changing this to rescue vcf?
</blockquote></details>

Done.
___
*[dxapp.json, line 99 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzJVOB-UeF5kZfxATm:-Mw11zmC8S-mg4w520HZ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/dxapp.json#L99)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

No new line at end of file
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline
</blockquote></details>

Done.
___
*[README.md, line 6 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzKBS71-5CmaC_GM0c:-Mw12-nw5oDFsbRPIEWo:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/README.md#L6)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

rescue list
</blockquote></details>

Done.
___
*[README.md, line 9 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzK8dEEtEvYmgTTJT0:-Mw120A5-IrW1Op--JcJ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/README.md#L9)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

rescue list
</blockquote></details>

Done.
___
*[README.md, line 14 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzKFB21ubuvYevxCi4:-Mw120QBARIuER-pjPX2:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/README.md#L14)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

rescue list
</blockquote></details>

Done.
___
*[README.md, line 18 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzKJJP1R3mlVwnLXW0:-Mw120nTEdYnbmXaozEw:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/README.md#L18)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

rescue list
</blockquote></details>

Done.
___
*[README.md, line 22 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzKQIJDItG1wkhlaXe:-Mw121GXEsrC108VeECj:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/README.md#L22)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

No new line at end of file
</blockquote></details>

Done.
___
*[src/eggd_tso500_rescue.sh, line 48 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzQbzk9DoZP6D0rSC6:-Mw1228R1ZOB5gtI_bd-:bctosgm) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/src/eggd_tso500_rescue.sh#L48)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

I'm being dim but what does this do?
</blockquote></details>

I couldn't find a way to add a flag to everything, i open to new ideas but that just adds the OPA flag in the Filter column to everything that has been retained before they are concatenated back with the REST
___
*[src/eggd_tso500_rescue.sh, line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzQp3JCFR8_t_-Ajg1:-Mw12EqIBX-fUv0LH0In:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/src/eggd_tso500_rescue.sh#L55)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Is there a reason that this isn't gzipped?
</blockquote></details>

Done.

**Review by woook — COMMENTED** [review]
Please talk to Jason about dearchival

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-:-MxZ_Gtt2KQjl0t9UyrQ:b-y8vnef)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @woook)

**Review by Addy81 — COMMENTED** [review]
I've rerun it and it is added to the confluence page https://cuhbioinformatics.atlassian.net/wiki/spaces/SOL/pages/2572419080/TSO500+rescue+v1.0.0

New job: https://platform.dnanexus.com/projects/G86K7XQ4jKXPgK4Z8Zj585Zj/monitor/job/G86PZJj4jKX8VKqJ6xQ63GxB

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-:-MxZaO4fCZRSiRJ9uepr:b3t787h)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @woook)

**Review by woook — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @Addy81 and @woook)

___
*[src/eggd_tso500_rescue.sh, line 48 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzQbzk9DoZP6D0rSC6:-Mx_pGd11zQ5mLhbN-dF:byg6mi2) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/src/eggd_tso500_rescue.sh#L48)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

I couldn't find a way to add a flag to everything, i open to new ideas but that just adds the OPA flag in the Filter column to everything that has been retained before they are concatenated back with the REST
</blockquote></details>

I see. 
How about we annotate matching sites with an OPA filter flag first and them remove what we don't want. We can then expand this idea to the whole thing, so that we end up with something like the following:

Get non-PASS | then add OPA | then retain only OPA
bcftools filter -i 'FILTER!="PASS"' ${sample_prefix}_norm.vcf.gz | bcftools filter -m + -s 'OPA' --mask-file ${hotspot_vcf_name} - | bcftools filter -i 'FILTER~"OPA"' - -o ${sample_prefix}.rescue.vcf.gz

Get PASS
bcftools filter -e 'FILTER!="PASS"' ${sample_prefix}_norm.vcf.gz -o ${sample_prefix}.pass.vcf.gz

Concat the two
bcftools concat -a  ${sample_prefix}_pass.vcf.gz ${sample_prefix}.rescue.vcf.gz -o ${sample_prefix}_withLowSupportHotspots.vcf.gz
___
*[src/eggd_tso500_rescue.sh, line 25 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-Mx_n76m25UhAaK9Uiko:-Mx_n76m25UhAaK9Uikp:bgzvg3z) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/39398a6ab6a8a368071cd950fd754b2d09106397/src/eggd_tso500_rescue.sh#L25)):*
> ```Shell
>     bcftools view -m2 $gvcf_name -o ${sample_prefix}.vcf
> 
>     # Remove chr prefix from patient vcf to match the reference genome
> ```

Can we add a comment that the "TSO500 app VCFs only contain chr1-22,X & Y and so this method is valid. However, this function should be reassessed if VCFs are created another way"



_Code quote:_
```Shell
Remove chr prefix from patient vcf to match the reference genome
```
___
*[src/eggd_tso500_rescue.sh, line 32 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MxZtJNR5E3nlsj9D6nn:-MxZtJNR5E3nlsj9D6no:b-b1t8lk) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/39398a6ab6a8a368071cd950fd754b2d09106397/src/eggd_tso500_rescue.sh#L32)):*
> ```Shell
>     -o ${sample_prefix}_norm.vcf
> 
>     bcftools norm -m -any -f genome.fa ${hotspot_vcf_name} \
> ```

Shouldn't hotspots VCF already normalised, aligned, sorted, gzipped? 
You could also provide the index.



_Code quote:_
```Shell
    bcftools norm -m -any -f genome.fa ${hotspot_vcf_name} \
    -o ${hotspot_vcf_prefix}_norm.vcf.gz -Oz
```
___
*[src/eggd_tso500_rescue.sh, line 40 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MxaSmk_2y1Nh_TIrzTC:-MxaSmk_2y1Nh_TIrzTD:b-c0ifst) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/39398a6ab6a8a368071cd950fd754b2d09106397/src/eggd_tso500_rescue.sh#L40)):*
> ```Shell
> 
>     # Create a vcf with only PASS variants
>     bcftools view -f .,PASS ${sample_prefix}_norm.vcf  -Oz \
> ```

Is the `.` needed



_Code quote:_
```Shell
.,PASS
```

**Review by Addy81 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @woook)

___
*[`src/eggd_tso500_rescue.sh` line 48 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzQbzk9DoZP6D0rSC6:-N561ngO9WRawX71VFZe:bbiohl9) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/src/eggd_tso500_rescue.sh#L48)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

I see. 
How about we annotate matching sites with an OPA filter flag first and them remove what we don't want. We can then expand this idea to the whole thing, so that we end up with something like the following:

Get non-PASS | then add OPA | then retain only OPA
bcftools filter -i 'FILTER!="PASS"' ${sample_prefix}_norm.vcf.gz | bcftools filter -m + -s 'OPA' --mask-file ${hotspot_vcf_name} - | bcftools filter -i 'FILTER~"OPA"' - -o ${sample_prefix}.rescue.vcf.gz

Get PASS
bcftools filter -e 'FILTER!="PASS"' ${sample_prefix}_norm.vcf.gz -o ${sample_prefix}.pass.vcf.gz

Concat the two
bcftools concat -a  ${sample_prefix}_pass.vcf.gz ${sample_prefix}.rescue.vcf.gz -o ${sample_prefix}_withLowSupportHotspots.vcf.gz

</blockquote></details>

code for this changed it needs testing.
___
*[`src/eggd_tso500_rescue.sh` line 25 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-Mx_n76m25UhAaK9Uiko:-MyBwK7x8B9yLhQpE6y0:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/39398a6ab6a8a368071cd950fd754b2d09106397/src/eggd_tso500_rescue.sh#L25)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Can we add a comment that the "TSO500 app VCFs only contain chr1-22,X & Y and so this method is valid. However, this function should be reassessed if VCFs are created another way"
</blockquote></details>

Done.
___
*[`src/eggd_tso500_rescue.sh` line 32 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MxZtJNR5E3nlsj9D6nn:-MyBxApkE84OUkOjn3aD:b-rbvnkz) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/39398a6ab6a8a368071cd950fd754b2d09106397/src/eggd_tso500_rescue.sh#L32)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Shouldn't hotspots VCF already normalised, aligned, sorted, gzipped? 
You could also provide the index.
</blockquote></details>

It wasn't at the time. I can normalise it but wanted to be on the safe side if using a different one?
___
*[`src/eggd_tso500_rescue.sh` line 40 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MxaSmk_2y1Nh_TIrzTC:-MyBxSUC0Kn5qtvCf71F:bt502rh) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/39398a6ab6a8a368071cd950fd754b2d09106397/src/eggd_tso500_rescue.sh#L40)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Is the `.` needed
</blockquote></details>

It also filters in .s in the Filter field in case there's not PASS or fail output.

**Comment by jethror1** [comment]
Made some formatting changes and switched to bcftools 1.15 asset.

Example job: https://platform.dnanexus.com/projects/GBkZXZj4Bj7bJ4kk4ffJJ0p8/monitor/job/GBp48B04Bj7z722Z4yzbyv1Q

OPA variants in output:
```
jethro@jethro-T490:~/Projects/eggd_tso500_rescue$ dx cat file-GBp4B504PvPBBgq04pz0P1G6 | zgrep -v '^#' | wc -l
1302
jethro@jethro-T490:~/Projects/eggd_tso500_rescue$ dx cat file-GBp4B504PvPBBgq04pz0P1G6 | zgrep -v '^#' | grep -v OPA  | wc -l
1227
jethro@jethro-T490:~/Projects/eggd_tso500_rescue$ dx cat file-GBp4B504PvPBBgq04pz0P1G6 | zgrep -v '^#' | grep  OPA  | wc -l
75
```

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @woook)

___
*[`src/eggd_tso500_rescue.sh` line 48 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MvzQbzk9DoZP6D0rSC6:-N5p1L1H5A4UKyHTfTcy:b-u9e521) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/3e45b678ae0c475d3efa5cfa810e2c58ae3c4ae7/src/eggd_tso500_rescue.sh#L48)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

code for this changed it needs testing.
</blockquote></details>

Done.


Example job: https://platform.dnanexus.com/projects/GBkZXZj4Bj7bJ4kk4ffJJ0p8/monitor/job/GBp48B04Bj7z722Z4yzbyv1Q

OPA variants in output:

```
jethro@jethro-T490:~/Projects/eggd_tso500_rescue$ dx cat file-GBp4B504PvPBBgq04pz0P1G6 | zgrep -v '^#' | wc -l
1302
jethro@jethro-T490:~/Projects/eggd_tso500_rescue$ dx cat file-GBp4B504PvPBBgq04pz0P1G6 | zgrep -v '^#' | grep -v OPA  | wc -l
1227
jethro@jethro-T490:~/Projects/eggd_tso500_rescue$ dx cat file-GBp4B504PvPBBgq04pz0P1G6 | zgrep -v '^#' | grep  OPA  | wc -l
75
```

**Review by woook — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @Addy81, @jethror1, and @woook)

___
*[`src/eggd_tso500_rescue.sh` line 40 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MxaSmk_2y1Nh_TIrzTC:-N5p6LLU73lScR2rhqzM:bj971wf) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/39398a6ab6a8a368071cd950fd754b2d09106397/src/eggd_tso500_rescue.sh#L40)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

It also filters in .s in the Filter field in case there's not PASS or fail output.
</blockquote></details>

Do we get `.`'s?
And if so, is it the correct logic to put this into the PASS VCF? How do they get treated later on? i.e. if there is an OPA variant that is `.`, would it be retained or chucked out?

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @woook)

___
*[`src/eggd_tso500_rescue.sh` line 40 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2#-MxaSmk_2y1Nh_TIrzTC:-N5pLjPvBxDHP9tU9ymd:b86066v) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/39398a6ab6a8a368071cd950fd754b2d09106397/src/eggd_tso500_rescue.sh#L40)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

Do we get `.`'s?
And if so, is it the correct logic to put this into the PASS VCF? How do they get treated later on? i.e. if there is an OPA variant that is `.`, would it be retained or chucked out?
</blockquote></details>

logic here would be any `.` and  `PASS` variants from patient VCF would always be retained.

Since these have filters applied from TSO app and `.` aren't present, going to remove the `.` (any that are also in the OPA VCF would be still brought back in with the `bcftools filter -i 'FILTER!="PASS"'` and soft filtering)

**Review by woook — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Addy81)

**Review by woook — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Addy81)

**Pull request merged**
