### PR TITLE
Initial working app

### PR DESCRIPTION
**Pull request by Addy81**
This app takes in the tso500 genomic vcf, filters reference calls out and filters whitelist variants from a given vcf. 

Example job:

https://platform.dnanexus.com/projects/G5697p84YV3xyf6j4byQG3zp/monitor/job/G69B2JQ4YV3jGxKX0X1zByxy

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1)

### CODE REVIEW

**Review by spaul91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Addy81 and @mattgarner)

___
*[dxapp.json, line 46 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpBVjP05PK3W9x73W2n:-MpBVjP05PK3W9x73W2o:b2cokki) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/fd2aa073ef73292dafc70f071aa0668b64c201ea/dxapp.json#L46)):*
> ```JSON
>     "distribution" : "Ubuntu",
>     "release": "20.04" ,
>     "version": "0", 
> ```

Is this whitespace at the end of the line?
___
*[README.md, line 18 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpBVHE0Ca1iq2ckuF-L:-MpBVHE0Ca1iq2ckuF-M:be5pt1u) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/fd2aa073ef73292dafc70f071aa0668b64c201ea/README.md#L18)):*
> ```Markdown
> ## What does this app output?
> This app outputs:
> * a vcf file with all PASS variants in addition to filtered in low quality variants given a whitelist of variants provided.
> ```

This is just for my own understanding, but how do the clinicians know the low quality variants can be trusted?
___
*[src/eggd_tso500_rescue.sh, line 16 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpBX0RqCf95AN9b9j5m:-MpBX0RqCf95AN9b9j5n:bpx29xb) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/fd2aa073ef73292dafc70f071aa0668b64c201ea/src/eggd_tso500_rescue.sh#L16)):*
> ```Shell
> 
>     # Get sample prefix
>     sample_prefix=$(echo "${gvcf_name/_MergedSmallVariants.genome.vcf/""}")
> ```

is `$gvcf_name` undefined or is it coming from somewhere else in the environment?

Is `sample_prefix` supposed to be something like this?

```shell
sample_prefix=$(basename ${gvcf} _MergedSmallVariants.genome.vcf)
echo $sample_prefix
PS208718-221847
```
___
*[src/eggd_tso500_rescue.sh, line 30 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpBf4qwBHlxEaBQPc9e:-MpBf4qy0xQ1E6qWA62O:b-hnqo2n) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/fd2aa073ef73292dafc70f071aa0668b64c201ea/src/eggd_tso500_rescue.sh#L30)):*
> ```Shell
>     bcftools index ${sample_prefix}_lowSupport.vcf.gz
>     bcftools index ${sample_prefix}_pass.vcf.gz
>     bcftools index ${hotspot_vcf_name} 
> ```

Is `$hotspot_vcf_name` defined outside the script or is it undefined here?

**Review by Addy81 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @mattgarner and @spaul91)

___
*[README.md, line 18 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpBVHE0Ca1iq2ckuF-L:-MpCgeDnDUGEyRsHZzcA:b-yszmfc) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/fd2aa073ef73292dafc70f071aa0668b64c201ea/README.md#L18)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

This is just for my own understanding, but how do the clinicians know the low quality variants can be trusted?
</blockquote></details>

We need to understand the difference between clinicians and clinical scientists here. Jon for example is a clinical scientist, and he will be doing the analysis. They don't now it can be trusted they want to make sure to see them and further confirm if there. 

Also need to remember that patients being tested through TSO500 have already been diagnosed with cancer. So a variant present which matches their phenotype will be probably there, so the scientists want to be able to pull those variants. Such variants if considered will go to a GTAB meeting where the scientists meet the clinicians and fully discuss the case and finding and come towards an informed agreement of the result before reporting it.
___
*[src/eggd_tso500_rescue.sh, line 16 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpBX0RqCf95AN9b9j5m:-MpCi2Qa1FUgZyy6zYXS:biyiahc) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/fd2aa073ef73292dafc70f071aa0668b64c201ea/src/eggd_tso500_rescue.sh#L16)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

is `$gvcf_name` undefined or is it coming from somewhere else in the environment?

Is `sample_prefix` supposed to be something like this?

```shell
sample_prefix=$(basename ${gvcf} _MergedSmallVariants.genome.vcf)
echo $sample_prefix
PS208718-221847
```
</blockquote></details>

any input can be accessed with _name _path and _prefix as seen here https://documentation.dnanexus.com/developer/apps/bash 
For some reason it wasn't working when I was writing this so i did it manually.
___
*[src/eggd_tso500_rescue.sh, line 30 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpBf4qwBHlxEaBQPc9e:-MpCjxrn8_bLPlukcSj9:bwptdnz) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/fd2aa073ef73292dafc70f071aa0668b64c201ea/src/eggd_tso500_rescue.sh#L30)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Is `$hotspot_vcf_name` defined outside the script or is it undefined here?
</blockquote></details>

$hotspot_vcf is an input and $hotspot_vcf_name uses the name of the file instead of the dnanexus file id as seen in the example link on the previous comment.

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1)* status: all files reviewed, 7 unresolved discussions (waiting on @Addy81, @mattgarner, and @spaul91)

___
*[src/eggd_tso500_rescue.sh, line 16 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpkVpIm2HNHlkJ8f7Ho:-MpkVpIm2HNHlkJ8f7Hp:b9r35ih) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/a5ab0b0c9d2e75c9825acf43372beb8ad040f931/src/eggd_tso500_rescue.sh#L16)):*
> ```Shell
> 
>     # Get sample prefix
>     sample_prefix=$(echo "${gvcf_name/_MergedSmallVariants.genome.vcf/""}")
> ```

I believe i understand what it's supposed to do but i'm surprised it works, especially the `"}"` bit
___
*[src/eggd_tso500_rescue.sh, line 27 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpkWbZq11AXMML6G9EP:-MpkWbZq11AXMML6G9EQ:bmuknwm) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/a5ab0b0c9d2e75c9825acf43372beb8ad040f931/src/eggd_tso500_rescue.sh#L27)):*
> ```Shell
>     bcftools view -f .,PASS ${sample_prefix}.vcf  -o  ${sample_prefix}_pass.vcf.gz -O z
> 
>     # Zip and index vcf files to use with bcftools isec command 
> ```

you are not using the isec cmd in this commented block of code
___
*[src/eggd_tso500_rescue.sh, line 32 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpkWZo557ivJ8DfpBj1:-MpkWZo557ivJ8DfpBj2:bb7phvt) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/a5ab0b0c9d2e75c9825acf43372beb8ad040f931/src/eggd_tso500_rescue.sh#L32)):*
> ```Shell
>     bcftools index ${hotspot_vcf_name} 
> 
>     # Intersect non-pass vcf with hospot list and keep sample vcf entries
> ```

typo
___
*[src/eggd_tso500_rescue.sh, line 52 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpkXNUi87v63a86XWYa:-MpkXNUi87v63a86XWYb:b-gae3wo) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/a5ab0b0c9d2e75c9825acf43372beb8ad040f931/src/eggd_tso500_rescue.sh#L52)):*
> ```Shell
>     # add output variables to your job's output as appropriate for the output
>     # class.  Run "dx-jobutil-add-output -h" for more information on what it
>     # does.
> ```


can be removed

**Review by Addy81 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @mattgarner, @spaul91, and @Yu-jinKim)

___
*[src/eggd_tso500_rescue.sh, line 16 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpkVpIm2HNHlkJ8f7Ho:-Mpkif081Z2CEFgaxdh9:b-lfz2pd) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/a5ab0b0c9d2e75c9825acf43372beb8ad040f931/src/eggd_tso500_rescue.sh#L16)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

I believe i understand what it's supposed to do but i'm surprised it works, especially the `"}"` bit
</blockquote></details>

https://stackoverflow.com/questions/13210880/replace-one-substring-for-another-string-in-shell-script 

I removed the echo as it was redundant but this is the syntax
___
*[src/eggd_tso500_rescue.sh, line 27 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpkWbZq11AXMML6G9EP:-MpkimOl3N-pnv-Zqrtt:bdiqyot) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/a5ab0b0c9d2e75c9825acf43372beb8ad040f931/src/eggd_tso500_rescue.sh#L27)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

you are not using the isec cmd in this commented block of code
</blockquote></details>

It says index the files to be used with the isec command as it only accepts gz and indexed files. :penguin: 
___
*[src/eggd_tso500_rescue.sh, line 32 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpkWZo557ivJ8DfpBj1:-MpkiwF-0lmhwmRpfw3u:b-x3rv5y) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/a5ab0b0c9d2e75c9825acf43372beb8ad040f931/src/eggd_tso500_rescue.sh#L32)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

typo
</blockquote></details>

fixed thanks
___
*[src/eggd_tso500_rescue.sh, line 52 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpkXNUi87v63a86XWYa:-Mpkixti1ia3i4Fs7Y5u:b-hfpv0l) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/a5ab0b0c9d2e75c9825acf43372beb8ad040f931/src/eggd_tso500_rescue.sh#L52)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

can be removed
</blockquote></details>

removed

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1)* status: all files reviewed, 2 unresolved discussions (waiting on @mattgarner and @spaul91)

**Review by spaul91 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-:-Mpl5EuA7u-GULvwXRU6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

___
*[src/eggd_tso500_rescue.sh, line 16 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500_rescue/1#-MpBX0RqCf95AN9b9j5m:-Mpl4vW7AY3cuKCZQT04:b7bmmqa) ([raw file](https://github.com/eastgenomics/eggd_tso500_rescue/blob/fd2aa073ef73292dafc70f071aa0668b64c201ea/src/eggd_tso500_rescue.sh#L16)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

any input can be accessed with _name _path and _prefix as seen here https://documentation.dnanexus.com/developer/apps/bash 
For some reason it wasn't working when I was writing this so i did it manually.
</blockquote></details>

Might be worth adding a quick comment referencing the docs to make it clear where this is coming from, but not necessary. Thanks for explaining, TIL :)

**Pull request closed without merging**
