### PR TITLE
URA-376 eggd vcf rescue v1.2.0 update src code

### PR DESCRIPTION
**Pull request by Aisha-D**
Update source code to include filtering of variants based on BCFtools filter

Latest job: https://platform.dnanexus.com/panx/projects/GgBvqP0421zvgj2P11Xqyg36/monitor/job/GgbP7Kj421zZ6q25v0g5b2JF

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @Aisha-D)

___
*[`dxapp.json` line 7 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSqNbZ9DTT5lIrjrcF:-NsSqNbZ9DTT5lIrjrcG:b-pc7kko) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/dxapp.json#L7)):*
> ```JSON
>   "properties": {
>     "githubRelease": "1.1.0"
>   },
> ```

can be removed



_Code quote:_
```JSON
  "properties": {
    "githubRelease": "1.1.0"
  },
```
___
*[`dxapp.json` line 9 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSqP2g9nDivl6MS85h:-NsSqP2g9nDivl6MS85i:b-8ktar2) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/dxapp.json#L9)):*
> ```JSON
>   },
>   "dxapi": "1.0.0",
>   "version": "1.1.0",
> ```

1.2.0



_Code quote:_
```JSON
1.1.0
```
___
*[`README.md` line 38 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSqUSo0_vqA6WqrzOc:-NsSqUSo0_vqA6WqrzOd:b-6fac61) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/README.md#L38)):*
> ```Markdown
> - `filter_tag` (`string`): tag to add to `FILTER` field of rescued variants (default: `rescued`), this will be appended to any existing FILTER fields (`bcftools filter -m +`).
> - `filter_tag_description` (`string`): additional description to append to FILTER line in header for provenance of rescued variants. Default description: `##FILTER=<ID={$filter_tag},Description="Record masked by region; variants added in eggd_vcf_rescue (DNAnexus job: $DX_JOB_ID)">`
> - `filter_string` (`string`): BCFtools filter command that can be used to filter variants in the filtered VCF even further within the app.The type of filterings that can be used by bcftools are all listed here: https://samtools.github.io/bcftools/bcftools.html
> ```

missing space



_Code quote:_
```Markdown
app.The
```
___
*[`src/eggd_vcf_rescue.sh` line 171 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSqbmgCuTZ_kBVTl5S:-NsSqbmgCuTZ_kBVTl5T:bvv0sd6) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/src/eggd_vcf_rescue.sh#L171)):*
> ```Shell
> 
>     # check number of enteries before variant quality filtering
>     num_var=$(cat "${filtered_vcf_name}" | grep -v ^"#" | wc -l)
> ```

this can directly just be `grep -v ^"#"  "${filtered_vcf_name}" ` to save on an extra command
___
*[`src/eggd_vcf_rescue.sh` line 172 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSqkLK0CG8TYcWeOqo:-NsSqkLK0CG8TYcWeOqp:bkyo72m) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/src/eggd_vcf_rescue.sh#L172)):*
> ```Shell
>     # check number of enteries before variant quality filtering
>     num_var=$(cat "${filtered_vcf_name}" | grep -v ^"#" | wc -l)
>     echo "VCF has $num_var variants before filtering poor quality variants"
> ```

filter string isn't necessarily poor quality since any filter can be applied



_Code quote:_
```Shell
filtering poor quality
```
___
*[`src/eggd_vcf_rescue.sh` line 175 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSr-m13wTBS8ZMGR4f:-NsSr-m13wTBS8ZMGR4g:b-harza0) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/src/eggd_vcf_rescue.sh#L175)):*
> ```Shell
> 
>     bgzip $filtered_vcf_name
>     tabix -p vcf "${filtered_vcf_name}.gz"
> ```

there's already a `_compress_and_index()` function if you wanna save a line



_Code quote:_
```Shell
    bgzip $filtered_vcf_name
    tabix -p vcf "${filtered_vcf_name}.gz"
```
___
*[`src/eggd_vcf_rescue.sh` line 180 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSr4Xi1hoycg3QjIYU:-NsSr4Xi1hoycg3QjIYV:b-pun6je) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/src/eggd_vcf_rescue.sh#L180)):*
> ```Shell
>     # check number of enteries after variant quality filtering
>     rm "${filtered_vcf_name}.gz"
>     num_var=$(cat "$filtered_vcf_name" | grep -v ^"#" | wc -l)
> ```

can be one command as above



_Code quote:_
```Shell
cat "$filtered_vcf_name" | grep -v ^"#" |
```
___
*[`src/eggd_vcf_rescue.sh` line 300 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSrAYL8YmRBqbC-LL0:-NsSrAYM-vdsJm1NoYRd:bw03k3l) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/src/eggd_vcf_rescue.sh#L300)):*
> ```Shell
>     if [[ $filter_string ]]; then
>         _filter_variants
>     fi
> ```

do we only want to do this when run as `_rescue_filtered` or also for `rescue_nonpass`?



_Code quote:_
```Shell
    # if variant filtering is set using BCFtools filtering command,
    # then run the filter_variants command
    if [[ $filter_string ]]; then
        _filter_variants
    fi
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @jethror1)

___
*[`dxapp.json` line 7 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSqNbZ9DTT5lIrjrcF:-NsSsDzR-bbPzBqe3I3z:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/dxapp.json#L7)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can be removed
</blockquote></details>

Done.
___
*[`dxapp.json` line 9 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSqP2g9nDivl6MS85h:-NsSsEJuBIaXoSkATg6b:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/dxapp.json#L9)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

1.2.0
</blockquote></details>

Done.
___
*[`README.md` line 38 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSqUSo0_vqA6WqrzOc:-NsSsRtz9ACHpWPT5TJk:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/README.md#L38)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing space
</blockquote></details>

Done.
___
*[`src/eggd_vcf_rescue.sh` line 171 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSqbmgCuTZ_kBVTl5S:-NsSt-vKAL0egWvdEDKV:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/src/eggd_vcf_rescue.sh#L171)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this can directly just be `grep -v ^"#"  "${filtered_vcf_name}" ` to save on an extra command
</blockquote></details>

Done.
___
*[`src/eggd_vcf_rescue.sh` line 172 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSqkLK0CG8TYcWeOqo:-NsSt09s7ZzXXkRQyA76:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/src/eggd_vcf_rescue.sh#L172)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

filter string isn't necessarily poor quality since any filter can be applied
</blockquote></details>

Done.
___
*[`src/eggd_vcf_rescue.sh` line 175 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSr-m13wTBS8ZMGR4f:-NsSt0Y73xdESf15NCbB:bw9m3lz) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/src/eggd_vcf_rescue.sh#L175)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

there's already a `_compress_and_index()` function if you wanna save a line
</blockquote></details>

Done. I had to add -f to the command bcause it would do it later on after filter_variants so it'll break as this one already exists
___
*[`src/eggd_vcf_rescue.sh` line 180 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSr4Xi1hoycg3QjIYU:-NsSt0sV73te27TXQCFh:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/src/eggd_vcf_rescue.sh#L180)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can be one command as above
</blockquote></details>

Done.

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @jethror1)

___
*[`src/eggd_vcf_rescue.sh` line 300 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSrAYL8YmRBqbC-LL0:-NsSzhXHCRePdHVX-Qm_:b-tvktpz) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/src/eggd_vcf_rescue.sh#L300)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

do we only want to do this when run as `_rescue_filtered` or also for `rescue_nonpass`?
</blockquote></details>

ive only rested for _rescue_filtered as that is what is of interest - however for rescue_nonpass i dont know.... i think the feature should be available

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`src/eggd_vcf_rescue.sh` line 300 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSrAYL8YmRBqbC-LL0:-NsT-oSFE4OwWSLL2tlu:b-kadavq) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/src/eggd_vcf_rescue.sh#L300)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

ive only rested for _rescue_filtered as that is what is of interest - however for rescue_nonpass i dont know.... i think the feature should be available
</blockquote></details>

well currently you have it inside the `_rescue_filtered` function, if we wanted to be able to use it on any as a last filtering step, it would want to go outside of here. I think it would also be good to add to the readme to be explicit that this is done _after_ the rescuing (i.e anything not passing this filter will still be removed)

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`src/eggd_vcf_rescue.sh` line 300 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsSrAYL8YmRBqbC-LL0:-NsT2emTA9BZTnyeJQi7:bby2rve) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/e23691d8c9adb2b4e135849ef2675b20d4584a34/src/eggd_vcf_rescue.sh#L300)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

well currently you have it inside the `_rescue_filtered` function, if we wanted to be able to use it on any as a last filtering step, it would want to go outside of here. I think it would also be good to add to the readme to be explicit that this is done _after_ the rescuing (i.e anything not passing this filter will still be removed)
</blockquote></details>

This is the confusing part, the filtering has to be before concatenating the filtered VCF to the rescued VCF

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Aisha-D)

___
*[`README.md` line 38 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsT5rrn9ppUTJ_ktU92:-NsT5rrn9ppUTJ_ktU93:bwvp3af) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/026b1123dc65769c6225da5f191c10df94e76b7e/README.md#L38)):*
> ```Markdown
> - `filter_tag` (`string`): tag to add to `FILTER` field of rescued variants (default: `rescued`), this will be appended to any existing FILTER fields (`bcftools filter -m +`).
> - `filter_tag_description` (`string`): additional description to append to FILTER line in header for provenance of rescued variants. Default description: `##FILTER=<ID={$filter_tag},Description="Record masked by region; variants added in eggd_vcf_rescue (DNAnexus job: $DX_JOB_ID)">`
> - `filter_string` (`string`): BCFtools filter command that can be used to filter variants in the filtered VCF even further within the app. The type of filterings that can be used by bcftools are all listed here: https://samtools.github.io/bcftools/bcftools.html
> ```

also could add an example filter string to the readme for completeness

**Review by jethror1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`README.md` line 38 at r3](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-NsT5rrn9ppUTJ_ktU92:-NsnlLwzBN-H01YLONHv:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_rescue/blob/026b1123dc65769c6225da5f191c10df94e76b7e/README.md#L38)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

also could add an example filter string to the readme for completeness
</blockquote></details>

Done.

**Review by Aisha-D — COMMENTED** [review]
Example of job that is for rescue nonpass: https://platform.dnanexus.com/panx/projects/GgBvqP0421zvgj2P11Xqyg36/monitor/job/Ggj95Gj421zb2p9Kg71bP49f

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-:-NsnlW6-4MVFtBYnmXv4:b2z5rgo)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Review by Aisha-D — COMMENTED** [review]
And a job for filtering VCF: https://platform.dnanexus.com/panx/projects/GgBvqP0421zvgj2P11Xqyg36/monitor/job/Ggj8xJ8421zbXzj41XzBy3gp

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7#-:-Nsnlc-3C7Y0JGiW-8Tq:byxuelr)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_rescue/7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
